[phases.setup]
nixPkgs = ["nodejs", "openssl"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm dlx serve out"

[variables]
NODE_ENV = "production"